---
- hosts: web
  tasks:
    - name: installs apache on Web Servers
      apt: pkg=apache2 state=present update_cache=true
      notify:
        - start apache2
  handlers:
    - name: start apache2
      service name=apache2 state=started
      
